const $=id=>document.getElementById(id),read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.open===id));scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openScreen(x.dataset.open));
document.querySelectorAll('.subtab').forEach(x=>x.onclick=()=>{document.querySelectorAll('.subtab').forEach(y=>y.classList.remove('active'));document.querySelectorAll('.subpanel').forEach(y=>y.classList.remove('active'));x.classList.add('active');$(x.dataset.sub).classList.add('active')});
function plan(goal,equipment,duration,level){const scale=level==='beginner'?.8:level==='advanced'?1.2:1,rounds=Math.max(2,Math.round(duration/10*scale));const p={'1.5 mile':['5-minute easy warm-up',`${Math.max(4,rounds+2)} × 400m at controlled hard pace with 90 sec recovery`,'3 × 12 walking lunges','3 × 30-sec plank','5-minute cool-down'],cooper:['8-minute easy run',`${Math.max(3,rounds)} × 3-minute hard / 2-minute easy`,'4 × 20-sec strides','Mobility cool-down'],popat:['5-minute dynamic warm-up',`${rounds} rounds: 20m shuttle, 10 burpees, 20 step-ups, 30-sec bear crawl`,'3 × 8 explosive push-ups','3 × 30-sec side plank each side'],general:['5-minute warm-up',`${rounds} rounds: 12 squats, 10 push-ups, 12 reverse lunges, 30-sec mountain climbers`,'10-minute steady cardio','Mobility cool-down']}[goal]||[];if(equipment==='dumbbells')p.splice(-1,0,'3 × 10 dumbbell rows and goblet squats');if(equipment==='gym')p.splice(-1,0,'3 × 8 leg press, cable row, and bench press');return p}
$('workoutForm').onsubmit=e=>{e.preventDefault();const d={goal:$('goal').value,equipment:$('equipment').value,duration:$('duration').value,level:$('level').value,date:new Date().toISOString()};d.plan=plan(d.goal,d.equipment,+d.duration,d.level);write('lastWorkout',d);renderWorkout(d);updateDashboard()};
function renderWorkout(d){$('workoutResult').classList.remove('hidden');$('workoutResult').innerHTML=`<span class="kicker">TODAY'S SESSION</span><h2>${d.duration}-minute ${esc(d.goal)} plan</h2><ol class="workout-list">${d.plan.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="muted">Stop for sharp pain, dizziness, chest pain, or unusual shortness of breath.</p>`}
$('runForm').onsubmit=e=>{e.preventDefault();const dist=+$('distance').value,total=+$('minutes').value*60 + +$('seconds').value;if(!dist||!total)return;const pace=total/dist,fmt=n=>`${Math.floor(n/60)}:${Math.round(n%60).toString().padStart(2,'0')}`,proj=pace*1.5,goal=+$('goalMinutes').value;write('lastRun',{distance:dist,total,pace,projection:proj,date:new Date().toISOString()});let goalLine='';if(goal){const diff=proj-goal*60;goalLine=`<p><b>${diff<=0?'On goal':'Time to cut'}:</b> ${Math.abs(Math.round(diff))} seconds ${diff<=0?'under':'over'} your 1.5-mile goal.</p>`}$('runResult').classList.remove('hidden');$('runResult').innerHTML=`<span class="kicker">RESULT</span><div class="result-number">${fmt(pace)} / mile</div><p>Projected 1.5-mile time: <b>${fmt(proj)}</b></p>${goalLine}`;updateDashboard()};
$('applicationForm').onsubmit=e=>{e.preventDefault();const a=read('applications');a.unshift({id:Date.now(),department:$('appDepartment').value.trim(),stage:$('appStage').value,date:$('appDate').value,notes:$('appNotes').value.trim()});write('applications',a);e.target.reset();renderApps();updateDashboard()};
function renderApps(){const a=read('applications');$('applicationList').innerHTML=a.length?a.map(x=>`<article class="item-card"><h3>${esc(x.department)}</h3><div class="meta">${esc(x.stage)}${x.date?' • '+esc(x.date):''}</div>${x.notes?`<p>${esc(x.notes)}</p>`:''}<div class="item-actions"><button class="danger" onclick="removeApp(${x.id})">Delete</button></div></article>`).join(''):'<div class="mission empty-state">No applications added yet.</div>'}window.removeApp=id=>{write('applications',read('applications').filter(x=>x.id!==id));renderApps();updateDashboard()};
$('departmentForm').onsubmit=e=>{e.preventDefault();const a=read('departments');a.unshift({id:Date.now(),name:$('deptName').value.trim(),url:$('deptUrl').value.trim(),type:$('deptType').value,verified:$('verifiedDate').value,details:$('deptDetails').value.trim()});write('departments',a);e.target.reset();$('verifiedDate').value=new Date().toISOString().slice(0,10);renderDepts();updateDashboard()};
$('departmentSearch').oninput=()=>renderDepts($('departmentSearch').value);
function renderDepts(q=''){const all=read('departments'),s=q.toLowerCase(),a=all.filter(x=>!s||`${x.name} ${x.type} ${x.details}`.toLowerCase().includes(s));$('departmentList').innerHTML=a.length?a.map(x=>`<article class="item-card"><h3>${esc(x.name)}</h3><div class="meta">${esc(x.type)} • Verified ${esc(x.verified)}</div>${x.details?`<p>${esc(x.details)}</p>`:''}<div class="item-actions"><a href="${esc(x.url)}" target="_blank" rel="noopener">Open official source ↗</a><button class="danger" onclick="removeDept(${x.id})">Delete</button></div></article>`).join(''):'<div class="mission empty-state">No matching official sources.</div>'}window.removeDept=id=>{write('departments',read('departments').filter(x=>x.id!==id));renderDepts();updateDashboard()};
$('settingsForm').onsubmit=e=>{e.preventDefault();write('testSettings',{name:$('testName').value.trim(),date:$('testDate').value});countdown();openScreen('home')};
function countdown(){const x=read('testSettings',{});$('testName').value=x.name||'';$('testDate').value=x.date||'';$('testLabel').textContent=(x.name||'NEXT TEST').toUpperCase();if(!x.date){$('countdownValue').textContent='Not set';return}const t=new Date();t.setHours(0,0,0,0);const days=Math.ceil((new Date(x.date+'T00:00:00')-t)/864e5);$('countdownValue').textContent=days>=0?`${days} day${days===1?'':'s'}`:'Date passed'}
function updateDashboard(){const apps=read('applications'),deps=read('departments'),w=read('lastWorkout',null),r=read('lastRun',null),fmt=n=>`${Math.floor(n/60)}:${Math.round(n%60).toString().padStart(2,'0')}`;$('applicationCount').textContent=apps.length;$('departmentCount').textContent=deps.length;$('runStat').textContent=r?fmt(r.projection):'—';$('todayMission').innerHTML=w?`<span class="kicker">${esc(w.level)} • ${esc(w.duration)} MIN</span><h2>${esc(w.goal)} session</h2><p>${w.plan.slice(0,3).map(esc).join(' • ')}</p>`:'Generate a workout to create today’s mission.'}
$('resetData').onclick=()=>{if(confirm('Delete all PoliceReady data saved in this browser?')){localStorage.clear();location.reload()}};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};
$('verifiedDate').value=new Date().toISOString().slice(0,10);renderApps();renderDepts();countdown();updateDashboard();const w=read('lastWorkout',null);if(w)renderWorkout(w);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
