const $=id=>document.getElementById(id),read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let compareIds=[],favoritesOnly=false;
function openScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.open===id));scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openScreen(x.dataset.open));
document.querySelectorAll('.subtab').forEach(x=>x.onclick=()=>{document.querySelectorAll('.subtab').forEach(y=>y.classList.remove('active'));document.querySelectorAll('.subpanel').forEach(y=>y.classList.remove('active'));x.classList.add('active');$(x.dataset.sub).classList.add('active')});
function favorites(){return read('favorites',[])}
function toggleFavorite(id){let a=favorites();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];write('favorites',a);renderDepartments();updateDashboard()}window.toggleFavorite=toggleFavorite;
function selectedCompare(id){compareIds=compareIds.includes(id)?compareIds.filter(x=>x!==id):compareIds.length<2?[...compareIds,id]:compareIds;renderDepartments();$('compareBtn').disabled=compareIds.length<2;$('compareBtn').textContent=`Compare (${compareIds.length})`}window.selectedCompare=selectedCompare;
function populateCounty(){const counties=[...new Set(DEPARTMENTS.flatMap(d=>d.county.split('/')))].sort();$('countyFilter').innerHTML='<option value="">All counties</option>'+counties.map(c=>`<option>${esc(c)}</option>`).join('')}
function renderDepartments(){const q=$('departmentSearch').value.toLowerCase(),county=$('countyFilter').value,status=$('statusFilter').value,favs=favorites();const list=DEPARTMENTS.filter(d=>(!q||`${d.name} ${d.city} ${d.county} ${d.state}`.toLowerCase().includes(q))&&(!county||d.county.split('/').includes(county))&&(!status||d.status===status)&&(!favoritesOnly||favs.includes(d.id)));$('departmentList').innerHTML=list.length?list.map(d=>`<article class="dept-card ${compareIds.includes(d.id)?'selected':''}"><div class="dept-top"><div><span class="status ${d.status}">${d.status==='verified'?'Verified summary':'Official source only'}</span><h3>${esc(d.name)}</h3><p>${esc(d.city)}, ${esc(d.state)} • ${esc(d.county)} County</p></div><button class="favorite ${favs.includes(d.id)?'active':''}" onclick="toggleFavorite(${d.id})" aria-label="Favorite">★</button></div><div class="dept-actions"><button class="secondary" onclick="openDepartment(${d.id})">View profile</button><button class="outline" onclick="selectedCompare(${d.id})">${compareIds.includes(d.id)?'Selected':'Compare'}</button></div></article>`).join(''):'<div class="mission empty-state">No matching departments.</div>'}
$('departmentSearch').oninput=renderDepartments;$('countyFilter').onchange=renderDepartments;$('statusFilter').onchange=renderDepartments;$('showFavorites').onclick=()=>{favoritesOnly=!favoritesOnly;$('showFavorites').textContent=`Favorites only: ${favoritesOnly?'On':'Off'}`;renderDepartments()};
function openDepartment(id){const d=DEPARTMENTS.find(x=>x.id===id),fav=favorites().includes(id);$('modalContent').innerHTML=`<span class="kicker">DEPARTMENT PROFILE</span><h1>${esc(d.name)}</h1><p class="muted">${esc(d.city)}, ${esc(d.state)} • ${esc(d.county)} County</p><div class="profile-status"><span class="status ${d.status}">${d.status==='verified'?'Verified summary':'Official source only'}</span>${d.verifiedDate?`<span>Verified ${esc(d.verifiedDate)}</span>`:''}</div><div class="profile-grid"><article><small>Minimum age</small><b>${esc(d.minimumAge)}</b></article><article><small>Education</small><b>${esc(d.education)}</b></article><article><small>Starting salary</small><b>${esc(d.salary)}</b></article><article><small>Fitness standards</small><b>${esc(d.fitness)}</b></article><article><small>Veteran preference</small><b>${esc(d.veteranPreference)}</b></article></div><article class="notice"><b>Current data status</b><p>${esc(d.summary)}</p></article><div class="modal-actions"><a class="primary link-btn" href="${esc(d.officialUrl)}" target="_blank" rel="noopener">Open official source ↗</a><button class="secondary" onclick="toggleFavorite(${d.id});openDepartment(${d.id})">${fav?'Remove favorite':'Save favorite'}</button><button class="outline" onclick="addToApplications(${d.id})">Track application</button></div>`;$('modal').classList.remove('hidden')}window.openDepartment=openDepartment;
$('closeModal').onclick=()=> $('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};
function addToApplications(id){const d=DEPARTMENTS.find(x=>x.id===id);$('modal').classList.add('hidden');openScreen('applications');$('appDepartment').value=d.name}$('compareBtn').onclick=()=>{if(compareIds.length<2)return;const [a,b]=compareIds.map(id=>DEPARTMENTS.find(x=>x.id===id));const rows=[['City',a.city,b.city],['County',a.county,b.county],['Minimum age',a.minimumAge,b.minimumAge],['Education',a.education,b.education],['Starting salary',a.salary,b.salary],['Fitness standards',a.fitness,b.fitness],['Veteran preference',a.veteranPreference,b.veteranPreference]];$('modalContent').innerHTML=`<span class="kicker">SIDE-BY-SIDE</span><h1>Department comparison</h1><div class="compare-table"><div class="compare-head"><b>Category</b><b>${esc(a.name)}</b><b>${esc(b.name)}</b></div>${rows.map(r=>`<div><span>${esc(r[0])}</span><span>${esc(r[1])}</span><span>${esc(r[2])}</span></div>`).join('')}</div><p class="muted">Fields marked “See official source” have not yet been summarized. Confirm current information directly with each agency.</p><div class="modal-actions"><a class="secondary link-btn" href="${esc(a.officialUrl)}" target="_blank">Open ${esc(a.city)} source ↗</a><a class="secondary link-btn" href="${esc(b.officialUrl)}" target="_blank">Open ${esc(b.city)} source ↗</a></div>`;$('modal').classList.remove('hidden')};
function plan(goal,equipment,duration,level){const scale=level==='beginner'?.8:level==='advanced'?1.2:1,rounds=Math.max(2,Math.round(duration/10*scale));const p={'1.5 mile':['5-minute easy warm-up',`${Math.max(4,rounds+2)} × 400m at controlled hard pace with 90 sec recovery`,'3 × 12 walking lunges','3 × 30-sec plank','5-minute cool-down'],cooper:['8-minute easy run',`${Math.max(3,rounds)} × 3-minute hard / 2-minute easy`,'4 × 20-sec strides','Mobility cool-down'],popat:['5-minute dynamic warm-up',`${rounds} rounds: 20m shuttle, 10 burpees, 20 step-ups, 30-sec bear crawl`,'3 × 8 explosive push-ups','3 × 30-sec side plank each side'],general:['5-minute warm-up',`${rounds} rounds: 12 squats, 10 push-ups, 12 reverse lunges, 30-sec mountain climbers`,'10-minute steady cardio','Mobility cool-down']}[goal]||[];if(equipment==='dumbbells')p.splice(-1,0,'3 × 10 dumbbell rows and goblet squats');if(equipment==='gym')p.splice(-1,0,'3 × 8 leg press, cable row, and bench press');return p}
$('workoutForm').onsubmit=e=>{e.preventDefault();const d={goal:$('goal').value,equipment:$('equipment').value,duration:$('duration').value,level:$('level').value,date:new Date().toISOString()};d.plan=plan(d.goal,d.equipment,+d.duration,d.level);write('lastWorkout',d);renderWorkout(d);updateDashboard()};
function renderWorkout(d){$('workoutResult').classList.remove('hidden');$('workoutResult').innerHTML=`<span class="kicker">TODAY'S SESSION</span><h2>${d.duration}-minute ${esc(d.goal)} plan</h2><ol class="workout-list">${d.plan.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="muted">Stop for sharp pain, dizziness, chest pain, or unusual shortness of breath.</p>`}
$('runForm').onsubmit=e=>{e.preventDefault();const dist=+$('distance').value,total=+$('minutes').value*60 + +$('seconds').value;if(!dist||!total)return;const pace=total/dist,fmt=n=>`${Math.floor(n/60)}:${Math.round(n%60).toString().padStart(2,'0')}`,proj=pace*1.5,goal=+$('goalMinutes').value;write('lastRun',{distance:dist,total,pace,projection:proj,date:new Date().toISOString()});let goalLine='';if(goal){const diff=proj-goal*60;goalLine=`<p><b>${diff<=0?'On goal':'Time to cut'}:</b> ${Math.abs(Math.round(diff))} seconds ${diff<=0?'under':'over'} your 1.5-mile goal.</p>`}$('runResult').classList.remove('hidden');$('runResult').innerHTML=`<span class="kicker">RESULT</span><div class="result-number">${fmt(pace)} / mile</div><p>Projected 1.5-mile time: <b>${fmt(proj)}</b></p>${goalLine}`;updateDashboard()};
$('applicationForm').onsubmit=e=>{e.preventDefault();const a=read('applications');a.unshift({id:Date.now(),department:$('appDepartment').value.trim(),stage:$('appStage').value,date:$('appDate').value,notes:$('appNotes').value.trim()});write('applications',a);e.target.reset();renderApps();updateDashboard()};
function renderApps(){const a=read('applications');$('applicationList').innerHTML=a.length?a.map(x=>`<article class="item-card"><h3>${esc(x.department)}</h3><div class="meta">${esc(x.stage)}${x.date?' • '+esc(x.date):''}</div>${x.notes?`<p>${esc(x.notes)}</p>`:''}<div class="item-actions"><button class="danger" onclick="removeApp(${x.id})">Delete</button></div></article>`).join(''):'<div class="mission empty-state">No applications added yet.</div>'}window.removeApp=id=>{write('applications',read('applications').filter(x=>x.id!==id));renderApps();updateDashboard()};
$('settingsForm').onsubmit=e=>{e.preventDefault();write('testSettings',{name:$('testName').value.trim(),date:$('testDate').value});countdown();openScreen('home')};
function countdown(){const x=read('testSettings',{});$('testName').value=x.name||'';$('testDate').value=x.date||'';$('testLabel').textContent=(x.name||'NEXT TEST').toUpperCase();if(!x.date){$('countdownValue').textContent='Not set';return}const t=new Date();t.setHours(0,0,0,0);const days=Math.ceil((new Date(x.date+'T00:00:00')-t)/864e5);$('countdownValue').textContent=days>=0?`${days} day${days===1?'':'s'}`:'Date passed'}
function updateDashboard(){const apps=read('applications'),favs=favorites(),w=read('lastWorkout',null),r=read('lastRun',null),fmt=n=>`${Math.floor(n/60)}:${Math.round(n%60).toString().padStart(2,'0')}`;$('directoryCount').textContent=DEPARTMENTS.length;$('favoriteCount').textContent=favs.length;$('applicationCount').textContent=apps.length;$('runStat').textContent=r?fmt(r.projection):'—';$('todayMission').innerHTML=w?`<span class="kicker">${esc(w.level)} • ${esc(w.duration)} MIN</span><h2>${esc(w.goal)} session</h2><p>${w.plan.slice(0,3).map(esc).join(' • ')}</p>`:'Generate a workout to create today’s mission.';const fd=DEPARTMENTS.filter(d=>favs.includes(d.id)).slice(0,4);$('homeFavorites').innerHTML=fd.length?fd.map(d=>`<button onclick="openDepartment(${d.id})"><b>${esc(d.city)}</b><small>${esc(d.name)}</small></button>`).join(''):'<div class="mission empty-state">Save departments to see them here.</div>'}
$('resetData').onclick=()=>{if(confirm('Delete all PoliceReady data saved in this browser?')){localStorage.clear();location.reload()}};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};
populateCounty();renderDepartments();renderApps();countdown();updateDashboard();const w=read('lastWorkout',null);if(w)renderWorkout(w);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
