const DEPARTMENTS = [
  ['Plano Police Department','Plano','Collin','TX','https://www.plano.gov/214/Police','source-only'],
  ['Frisco Police Department','Frisco','Collin/Denton','TX','https://www.friscotexas.gov/239/Police','source-only'],
  ['Allen Police Department','Allen','Collin','TX','https://www.cityofallen.org/906/Police','source-only'],
  ['McKinney Police Department','McKinney','Collin','TX','https://www.mckinneytexas.org/166/Police','source-only'],
  ['Richardson Police Department','Richardson','Dallas/Collin','TX','https://www.cor.net/departments/police','source-only'],
  ['Wylie Police Department','Wylie','Collin/Dallas/Rockwall','TX','https://www.wylietexas.gov/departments/police_department/index.php','source-only'],
  ['Murphy Police Department','Murphy','Collin','TX','https://www.murphytx.org/115/Police','source-only'],
  ['Prosper Police Department','Prosper','Collin/Denton','TX','https://www.prospertx.gov/department/police/','source-only'],
  ['Celina Police Department','Celina','Collin/Denton','TX','https://www.celina-tx.gov/888/Police-Department','source-only'],
  ['Princeton Police Department','Princeton','Collin','TX','https://princetontx.gov/214/Police','source-only'],
  ['Anna Police Department','Anna','Collin','TX','https://www.annatexas.gov/117/Police','source-only'],
  ['Melissa Police Department','Melissa','Collin','TX','https://www.cityofmelissa.com/190/Police-Department','source-only'],
  ['Dallas Police Department','Dallas','Dallas','TX','https://dallascityhall.com/departments/police/Pages/default.aspx','source-only'],
  ['Garland Police Department','Garland','Dallas','TX','https://www.garlandtx.gov/192/Police','source-only'],
  ['Irving Police Department','Irving','Dallas','TX','https://www.cityofirving.org/940/Police','source-only'],
  ['Mesquite Police Department','Mesquite','Dallas/Kaufman','TX','https://www.cityofmesquite.com/454/Police','source-only'],
  ['Carrollton Police Department','Carrollton','Dallas/Denton/Collin','TX','https://www.cityofcarrollton.com/departments/departments-g-p/police','source-only'],
  ['Farmers Branch Police Department','Farmers Branch','Dallas','TX','https://www.farmersbranchtx.gov/158/Police','source-only'],
  ['Coppell Police Department','Coppell','Dallas/Denton','TX','https://www.coppelltx.gov/402/Police','source-only'],
  ['Rowlett Police Department','Rowlett','Dallas/Rockwall','TX','https://www.rowletttx.gov/199/Police','source-only'],
  ['DeSoto Police Department','DeSoto','Dallas','TX','https://www.ci.desoto.tx.us/151/Police','source-only'],
  ['Duncanville Police Department','Duncanville','Dallas','TX','https://www.duncanvilletx.gov/departments/police/','source-only'],
  ['Cedar Hill Police Department','Cedar Hill','Dallas/Ellis','TX','https://www.cedarhilltx.com/196/Police','source-only'],
  ['Lancaster Police Department','Lancaster','Dallas','TX','https://www.lancaster-tx.com/155/Police','source-only'],
  ['Grand Prairie Police Department','Grand Prairie','Dallas/Tarrant/Ellis','TX','https://www.gptx.org/Departments/Police-Department','source-only'],
  ['Addison Police Department','Addison','Dallas','TX','https://addisontexas.net/police','source-only'],
  ['University Park Police Department','University Park','Dallas','TX','https://www.uptexas.org/312/Police','source-only'],
  ['Highland Park Department of Public Safety','Highland Park','Dallas','TX','https://www.hptx.org/189/Public-Safety','source-only'],
  ['Balch Springs Police Department','Balch Springs','Dallas','TX','https://www.cityofbalchsprings.com/148/Police-Department','source-only'],
  ['Sachse Police Department','Sachse','Dallas/Collin','TX','https://www.cityofsachse.com/168/Police','source-only'],
  ['Fort Worth Police Department','Fort Worth','Tarrant/Denton/Parker/Wise','TX','https://www.fortworthtexas.gov/departments/police','source-only'],
  ['Arlington Police Department','Arlington','Tarrant','TX','https://www.arlingtontx.gov/city_hall/departments/police','source-only'],
  ['Grapevine Police Department','Grapevine','Tarrant/Dallas/Denton','TX','https://www.grapevinetexas.gov/450/Police','source-only'],
  ['Southlake Police Department','Southlake','Tarrant/Denton','TX','https://www.cityofsouthlake.com/169/Police','source-only'],
  ['Euless Police Department','Euless','Tarrant','TX','https://www.eulesstx.gov/departments/police','source-only'],
  ['Bedford Police Department','Bedford','Tarrant','TX','https://www.bedfordtx.gov/174/Police-Department','source-only'],
  ['Hurst Police Department','Hurst','Tarrant','TX','https://www.hursttx.gov/about-us/departments/police-department','source-only'],
  ['North Richland Hills Police Department','North Richland Hills','Tarrant','TX','https://www.nrhtx.com/270/Police','source-only'],
  ['Keller Police Department','Keller','Tarrant','TX','https://www.cityofkeller.com/services/police','source-only'],
  ['Mansfield Police Department','Mansfield','Tarrant/Johnson/Ellis','TX','https://www.mansfieldtexas.gov/168/Police','source-only'],
  ['Burleson Police Department','Burleson','Johnson/Tarrant','TX','https://www.burlesontx.com/70/Police','source-only'],
  ['Colleyville Police Department','Colleyville','Tarrant','TX','https://www.colleyville.com/government/departments-a-l/police','source-only'],
  ['Watauga Police Department','Watauga','Tarrant','TX','https://www.cowtx.org/141/Police','source-only'],
  ['White Settlement Police Department','White Settlement','Tarrant','TX','https://www.wstx.us/166/Police','source-only'],
  ['Benbrook Police Department','Benbrook','Tarrant','TX','https://www.benbrook-tx.gov/171/Police','source-only'],
  ['Denton Police Department','Denton','Denton','TX','https://www.cityofdenton.com/351/Police','source-only'],
  ['Lewisville Police Department','Lewisville','Denton','TX','https://www.cityoflewisville.com/about-us/city-departments/police-department','source-only'],
  ['Flower Mound Police Department','Flower Mound','Denton/Tarrant','TX','https://www.flower-mound.com/139/Police-Department','source-only'],
  ['The Colony Police Department','The Colony','Denton','TX','https://www.thecolonytx.gov/162/Police','source-only'],
  ['Little Elm Police Department','Little Elm','Denton','TX','https://www.littleelm.org/289/Police-Department','source-only'],
  ['Lake Dallas Police Department','Lake Dallas','Denton','TX','https://www.lakedallas.com/174/Police-Department','source-only'],
  ['Corinth Police Department','Corinth','Denton','TX','https://www.cityofcorinth.com/police','source-only'],
  ['Highland Village Police Department','Highland Village','Denton','TX','https://www.highlandvillage.org/168/Police','source-only'],
  ['Rockwall Police Department','Rockwall','Rockwall','TX','https://www.rockwall.com/police.asp','source-only'],
  ['Heath Department of Public Safety','Heath','Rockwall','TX','https://www.heathtx.com/departments/public-safety/','source-only'],
  ['Royse City Police Department','Royse City','Rockwall/Collin/Hunt','TX','https://www.roysecity.com/145/Police-Department','source-only'],
  ['Forney Police Department','Forney','Kaufman','TX','https://www.forneytx.gov/218/Police','source-only'],
  ['Kaufman Police Department','Kaufman','Kaufman','TX','https://www.kaufmantx.org/2171/Police-Department','source-only'],
  ['Terrell Police Department','Terrell','Kaufman','TX','https://www.cityofterrell.org/159/Police-Department','source-only'],
  ['Waxahachie Police Department','Waxahachie','Ellis','TX','https://www.waxahachie.com/departments/police_department/index.php','source-only'],
  ['Midlothian Police Department','Midlothian','Ellis','TX','https://www.midlothian.tx.us/166/Police','source-only'],
  ['Ennis Police Department','Ennis','Ellis','TX','https://www.ennistx.gov/departments/police','source-only'],
  ['Sherman Police Department','Sherman','Grayson','TX','https://www.ci.sherman.tx.us/111/Police','source-only'],
  ['Denison Police Department','Denison','Grayson','TX','https://www.cityofdenison.com/214/Police','source-only']
].map((d,i)=>({id:i+1,name:d[0],city:d[1],county:d[2],state:d[3],officialUrl:d[4],applyUrl:d[4],status:d[5],verifiedDate:'',summary:'Official department or city page linked. Detailed hiring, salary, and fitness fields have not yet been summarized in PoliceReady. Confirm all current requirements directly with the agency.',minimumAge:'See official source',education:'See official source',salary:'See official source',benefits:'See official source',hiringProcess:'See official source',fitness:'See official source',veteranPreference:'See official source',fitnessVerified:false,fitnessType:'general',fitnessEvents:[],sourceLinks:[{label:'Official department or city page',url:d[4]}]}));

Object.assign(DEPARTMENTS.find(d=>d.city==='Plano'),{status:'verified',verifiedDate:'2026-07-30',minimumAge:'21+ (official eligibility page)',education:'Multiple qualifying paths; confirm on official eligibility page',fitness:'Two-part physical agility test; official requirements page and video',hiringProcess:'Written and physical testing followed by agency hiring steps',fitnessVerified:true,fitnessType:'obstacle',fitnessEvents:[{name:'Physical Agility Test',standard:'Two-part applicant test',note:'Use the official requirements page and video for current course details.'}],officialUrl:'https://www.plano.gov/police-employment',applyUrl:'https://www.plano.gov/police-employment',sourceLinks:[{label:'Police employment',url:'https://www.plano.gov/police-employment'},{label:'Fitness requirements',url:'https://www.plano.gov/fitness-requirements'},{label:'Eligibility and disqualifiers',url:'https://www.plano.gov/eligibility-disqualifiers'}],summary:'PoliceReady summarizes the test type and eligibility information from official City of Plano pages. Exact course rules and passing requirements must be checked on the linked official fitness page.'});

Object.assign(DEPARTMENTS.find(d=>d.city==='Frisco'),{status:'verified',verifiedDate:'2026-07-30',salary:'FY26 recruit pay plan published by the City of Frisco',fitness:'2,000-meter Concept2 row; minimum 50% standard based on age, weight, and gender',hiringProcess:'Application and pre-employment process through the official city career system',fitnessVerified:true,fitnessType:'row',fitnessEvents:[{name:'2,000-meter row',standard:'Minimum 50%',note:'Concept2 rower, damper setting 5; standard varies by age, weight, and gender.'}],officialUrl:'https://www.friscotexas.gov/300/Career-Opportunities',applyUrl:'https://www.friscotexas.gov/300/Career-Opportunities',sourceLinks:[{label:'Police career opportunities',url:'https://www.friscotexas.gov/300/Career-Opportunities'},{label:'Recruiting FAQ / row standard',url:'https://www.friscotexas.gov/faq.aspx?TID=31'},{label:'FY26 police pay plan',url:'https://www.friscotexas.gov/DocumentCenter/View/39761/FY26-Police-Pay-Plan-v1205'}],summary:'Official Frisco sources describe a 2,000-meter Concept2 row assessment and a 50% minimum that varies by applicant characteristics. Use the official calculator and current recruiting instructions before testing.'});
